Strong4VM: /mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/api/api_example.cc File Reference
api_example.cc File Reference
#include "BackboneSolverAPI.hh"
#include <iostream>
#include <string>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 12 of file api_example.cc.
References BackboneSolverAPI::compute_backbone(), BackboneSolverAPI::create_backbone_detector(), BackboneSolverAPI::get_max_variable(), BackboneSolverAPI::print_backbone(), and BackboneSolverAPI::read_dimacs().