Strong4VM: Dimacs2GraphsAPI::Impl Class Reference
Dimacs2GraphsAPI::Impl Class Reference
PIMPL (Pointer to Implementation) idiom for ABI stability.
Classes
struct ThreadWorker
Thread worker structure for parallel variable processing.
Public Member Functions
Impl ()
string normalize_path (const string &path)
Normalizes a file path by removing trailing slashes.
string get_basename (const string &filepath)
Extracts the basename from a file path.
string get_directory (const string &filepath)
Extracts the directory path from a file path.
bool read_clause_count (const string &dimacs_path, int &clauses)
Reads the clause count from a DIMACS file header.
bool read_feature_names (const string &dimacs_path, map< int, string > &feature_map, vector< bool > &aux_vars)
Reads feature names from DIMACS comments and identifies auxiliary variables.
bool generate_graphs_impl (const string &dimacs_file, const string &output_folder, const string &detector, int num_of_threads)
Internal implementation of graph generation.
Public Attributes
BoneDiggerAPI bone_api
int num_variables
int num_clauses
vector< int > global_backbone
string error_message
bool filter_auxiliary
Detailed Description
PIMPL (Pointer to Implementation) idiom for ABI stability.
This implementation class encapsulates all internal state and implementation details of the Dimacs2GraphsAPI. Using the PIMPL idiom provides:
ABI Stability: Changes to internal implementation do not affect binary compatibility
Compilation Firewall: Reduces compilation dependencies and improves build times
Information Hiding: Keeps implementation details private
Encapsulated components:
BoneDiggerAPI instance for SAT-based backbone detection
Formula statistics (number of variables and clauses)
Global backbone vector (core and dead features)
File path utilities (basename extraction, directory handling, path normalization)
Thread coordination structures and worker management
Error message storage for diagnostic reporting
Definition at line 102 of file Dimacs2GraphsAPI.cc.
Constructor & Destructor Documentation
Impl()
Impl () inline
Definition at line 111 of file Dimacs2GraphsAPI.cc.
Member Function Documentation
generate_graphs_impl()
bool generate_graphs_impl (const string & dimacs_file, const string & output_folder, const string & detector, int num_of_threads) inline
Internal implementation of graph generation.
This is the main algorithm that orchestrates the entire graph generation pipeline:
Pipeline Overview:
Load DIMACS file and create backbone detector
Compute global backbone (core and dead features)
Validate thread count against CPU cores
Process variables (single-threaded or multi-threaded):
For each non-backbone variable v, compute backbone assuming v=true
Extract requires and excludes edges based on forced assignments
Extract feature names from DIMACS comments
Generate output files (Pajek graphs and feature lists)
Threading Strategy:
Single-threaded mode: Sequential processing with immediate output
Multi-threaded mode:
Pre-create all BoneDiggerAPI instances in main thread (CRITICAL)
Create ThreadWorker instances with pre-initialized solvers
Launch worker threads with static range partitioning
Monitor progress with atomic counter
Merge results from thread-local buffers after join
Thread Count Validation:
Minimum: 1 thread
Maximum: Number of CPU cores (fail-fast if exceeded)
Effective: min(requested_threads, num_variables)
Parameters
dimacs_file Path to input DIMACS file (with or without .dimacs extension)
output_folder Output directory (empty string uses input file directory)
detector Backbone detector algorithm name (e.g., "CheckCandidatesOneByOne")
num_of_threads Number of threads for parallel processing (1 for sequential)
Returns
true if successful, false on error (error message in error_message field)
Note
The formula must be satisfiable. UNSAT formulas are not supported.
Thread count exceeding CPU cores will fail with an error message.
See also
BoneDiggerAPI::create_backbone_detector() for available detector algorithms
ThreadWorker for parallel processing implementation
Definition at line 448 of file Dimacs2GraphsAPI.cc.
References bone_api, BoneDiggerAPI::compute_backbone(), BoneDiggerAPI::compute_backbone_with_assumptions(), BoneDiggerAPI::create_backbone_detector(), error_message, filter_auxiliary, get_basename(), get_directory(), BoneDiggerAPI::get_max_variable(), global_backbone, normalize_path(), num_clauses, num_variables, read_clause_count(), BoneDiggerAPI::read_dimacs(), and read_feature_names().
Referenced by Dimacs2GraphsAPI::generate_graphs().
get_basename()
string get_basename (const string & filepath) inline
Extracts the basename from a file path.
Removes the directory path and .dimacs extension (if present) from a file path. This is used to generate consistent output file names.
Parameters
filepath The full file path (e.g., "/path/to/model.dimacs")
Returns
Basename without directory or extension (e.g., "model")
Definition at line 139 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl().
get_directory()
string get_directory (const string & filepath) inline
Extracts the directory path from a file path.
Returns the directory component of a file path, or "." if no directory component is present.
Parameters
filepath The full file path
Returns
Directory path, or "." for current directory
Definition at line 160 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl().
normalize_path()
string normalize_path (const string & path) inline
Normalizes a file path by removing trailing slashes.
Ensures consistent path representation across platforms by removing trailing directory separators (both forward and backward slashes).
Parameters
path The path to normalize
Returns
Normalized path without trailing slashes
Definition at line 122 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl().
read_clause_count()
bool read_clause_count (const string & dimacs_path, int & clauses) inline
Reads the clause count from a DIMACS file header.
Parses the DIMACS problem line (p cnf [vars] [clauses]) to extract the number of clauses. This information is stored separately as it's not provided by the BoneDiggerAPI.
Parameters
dimacs_path Path to the DIMACS file
clauses Output parameter to store the clause count
Returns
true if successful, false on error
Definition at line 177 of file Dimacs2GraphsAPI.cc.
References error_message.
Referenced by generate_graphs_impl().
read_feature_names()
bool read_feature_names (const string & dimacs_path, map< int, string > & feature_map, vector< bool > & aux_vars) inline
Reads feature names from DIMACS comments and identifies auxiliary variables.
Parses comment lines in the format "c [var_num] [feature_name]" to build a map of variable numbers to feature names. Also identifies variables whose names start with "aux_" (Tseitin auxiliary variables).
Parameters
dimacs_path Path to the DIMACS file
feature_map Output map of variable numbers to feature names
aux_vars Output set of auxiliary variable indices
Returns
true if successful, false on error
Definition at line 213 of file Dimacs2GraphsAPI.cc.
References error_message.
Referenced by generate_graphs_impl().
Member Data Documentation
bone_api
BoneDiggerAPI bone_api
Definition at line 104 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl().
error_message
string error_message
Definition at line 108 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl(), Dimacs2GraphsAPI::get_error_message(), read_clause_count(), and read_feature_names().
filter_auxiliary
bool filter_auxiliary
Definition at line 109 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl(), and Dimacs2GraphsAPI::set_filter_auxiliary().
global_backbone
vector<int> global_backbone
Definition at line 107 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl(), and Dimacs2GraphsAPI::get_global_backbone().
num_clauses
int num_clauses
Definition at line 106 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl(), and Dimacs2GraphsAPI::get_num_clauses().
num_variables
int num_variables
Definition at line 105 of file Dimacs2GraphsAPI.cc.
Referenced by generate_graphs_impl(), and Dimacs2GraphsAPI::get_num_variables().
The documentation for this class was generated from the following file:
/mnt/c/improving_strong4vm/strong4vm/dimacs2graphs/api/Dimacs2GraphsAPI.cc