Strong4VM: Dimacs2GraphsAPI Class Reference
Dimacs2GraphsAPI Class Reference
Parallel Graph Generation
Main API class for generating transitive graphs from DIMACS CNF formulas.
#include <Dimacs2GraphsAPI.hh>
Classes
class Impl
PIMPL (Pointer to Implementation) idiom for ABI stability.
Public Member Functions
Dimacs2GraphsAPI ()
Constructor.
~Dimacs2GraphsAPI ()
Destructor.
bool generate_graphs (const std::string &dimacs_file, const std::string &output_folder="", const std::string &detector="one", int num_of_threads=1)
Generate graph files from a DIMACS CNF formula.
int get_num_variables () const
Get the number of variables in the last processed formula.
int get_num_clauses () const
Get the number of clauses in the last processed formula.
std::vector< int > get_global_backbone () const
Get the global backbone computed for the last processed formula.
std::string get_error_message () const
Get the last error message.
void set_filter_auxiliary (bool filter)
Set whether to filter auxiliary variables from output.
Detailed Description
Main API class for generating transitive graphs from DIMACS CNF formulas.
This class provides a simple interface to:
Load a DIMACS CNF file
Compute backbone relationships using Backbone Solver
Generate graph output files (requires.net, excludes.net, core.txt, dead.txt)
Definition at line 152 of file Dimacs2GraphsAPI.hh.
Constructor & Destructor Documentation
Dimacs2GraphsAPI()
Dimacs2GraphsAPI ()
Constructor.
Constructor - creates PIMPL instance.
Definition at line 827 of file Dimacs2GraphsAPI.cc.
~Dimacs2GraphsAPI()
~Dimacs2GraphsAPI ()
Destructor.
Destructor - cleans up PIMPL instance.
Definition at line 832 of file Dimacs2GraphsAPI.cc.
Member Function Documentation
generate_graphs()
bool generate_graphs (const std::string & dimacs_file, const std::string & output_folder = "", const std::string & detector = "one", int num_of_threads = 1)
Generate graph files from a DIMACS CNF formula.
Generates dependency graphs from a DIMACS CNF formula.
Parameters
dimacs_file Path to the input DIMACS file (with or without .dimacs extension)
output_folder Optional output folder path (default: same as input file location)
detector Backbone detector to use: "one" (default) or "without"
"one": CheckCandidatesOneByOne with activity bumping (recommended)
"without": CheckCandidatesOneByOneWithoutAttention (baseline)
num_of_threads Number of threads to use for parallel processing (default: 1) Must not exceed available CPU cores
Returns
true if successful, false otherwise
Output files created:
[basename]__requires.net : Pajek format directed graph (requires relationships)
[basename]__excludes.net : Pajek format undirected graph (excludes relationships)
[basename]__core.txt : Core features (positive backbone literals)
[basename]__dead.txt : Dead features (negative backbone literals)
Public API entry point that delegates to the PIMPL implementation. See Dimacs2GraphsAPI.hh for detailed parameter documentation.
See also
generate_graphs_impl() for detailed implementation documentation
Definition at line 844 of file Dimacs2GraphsAPI.cc.
References Dimacs2GraphsAPI::Impl::generate_graphs_impl().
Referenced by main(), and Strong4VMAPI::Impl::perform_analysis().
get_error_message()
string get_error_message () const
Get the last error message.
Gets the last error message.
Returns
Error message string (empty if no error)
Definition at line 881 of file Dimacs2GraphsAPI.cc.
References Dimacs2GraphsAPI::Impl::error_message.
Referenced by main(), and Strong4VMAPI::Impl::perform_analysis().
get_global_backbone()
vector< int > get_global_backbone () const
Get the global backbone computed for the last processed formula.
Gets the global backbone of the formula.
Returns
Vector of backbone literals (empty if no formula has been processed)
Vector of literals in the backbone (positive for core, negative for dead)
Definition at line 873 of file Dimacs2GraphsAPI.cc.
References Dimacs2GraphsAPI::Impl::global_backbone.
Referenced by main(), and Strong4VMAPI::Impl::perform_analysis().
get_num_clauses()
int get_num_clauses () const
Get the number of clauses in the last processed formula.
Gets the number of clauses in the loaded formula.
Returns
Number of clauses, or 0 if no formula has been processed
Number of clauses
Definition at line 865 of file Dimacs2GraphsAPI.cc.
References Dimacs2GraphsAPI::Impl::num_clauses.
Referenced by main(), and Strong4VMAPI::Impl::perform_analysis().
get_num_variables()
int get_num_variables () const
Get the number of variables in the last processed formula.
Gets the number of variables in the loaded formula.
Returns
Number of variables, or 0 if no formula has been processed
Number of variables
Definition at line 857 of file Dimacs2GraphsAPI.cc.
References Dimacs2GraphsAPI::Impl::num_variables.
Referenced by main(), and Strong4VMAPI::Impl::perform_analysis().
set_filter_auxiliary()
void set_filter_auxiliary (bool filter)
Set whether to filter auxiliary variables from output.
Sets whether to filter auxiliary variables.
When enabled, variables whose names start with "aux_" (Tseitin auxiliary variables) will be excluded from:
The main iteration loop (for efficiency)
Core and dead feature lists
Requires and excludes graph edges
Parameters
filter If true, filter auxiliary variables (default: false)
filter If true, variables starting with "aux_" are excluded
Definition at line 889 of file Dimacs2GraphsAPI.cc.
References Dimacs2GraphsAPI::Impl::filter_auxiliary.
The documentation for this class was generated from the following files:
/mnt/c/improving_strong4vm/strong4vm/dimacs2graphs/api/Dimacs2GraphsAPI.hh
/mnt/c/improving_strong4vm/strong4vm/dimacs2graphs/api/Dimacs2GraphsAPI.cc