Strong4VM: const_LiteralSetIterator Class Reference
const_LiteralSetIterator Class Reference
Standard forward iterator for LiteralSet.
#include <LiteralSet.hh>
Public Member Functions
const_LiteralSetIterator (const LiteralSet &ls, size_t x)
Construct an iterator.
const_LiteralSetIterator (const const_LiteralSetIterator &mit)
Copy constructor.
const_LiteralSetIterator & operator++ ()
Advance to next literal.
const Lit operator* () const
Dereference to get current literal.
bool operator== (const const_LiteralSetIterator &rhs)
Equality comparison.
bool operator!= (const const_LiteralSetIterator &rhs)
Inequality comparison.
Detailed Description
Standard forward iterator for LiteralSet.
Provides standard C++ forward iterator semantics for iterating through all literals in a LiteralSet exactly once.
Definition at line 87 of file LiteralSet.hh.
Constructor & Destructor Documentation
const_LiteralSetIterator() [1/2]
const_LiteralSetIterator (const LiteralSet & ls, size_t x)
Construct an iterator.
Parameters
ls The LiteralSet to iterate over
x Starting position (index in internal storage)
Definition at line 16 of file LiteralSet.cc.
References LiteralSet::get(), and LiteralSet::physical_size().
const_LiteralSetIterator() [2/2]
const_LiteralSetIterator (const const_LiteralSetIterator & mit) inline
Copy constructor.
Parameters
mit Iterator to copy from
Definition at line 101 of file LiteralSet.hh.
Member Function Documentation
operator!=()
bool operator!= (const const_LiteralSetIterator & rhs) inline
Inequality comparison.
Parameters
rhs Iterator to compare with
Returns
true if iterators point to different positions
Definition at line 131 of file LiteralSet.hh.
operator*()
const Lit operator* () const inline
Dereference to get current literal.
Returns
The current literal
Definition at line 311 of file LiteralSet.hh.
References LiteralSet::get().
operator++()
const_LiteralSetIterator & operator++ () inline
Advance to next literal.
Returns
Reference to this iterator
Definition at line 304 of file LiteralSet.hh.
References LiteralSet::get(), and LiteralSet::physical_size().
operator==()
bool operator== (const const_LiteralSetIterator & rhs) inline
Equality comparison.
Parameters
rhs Iterator to compare with
Returns
true if iterators point to same position
Definition at line 121 of file LiteralSet.hh.
The documentation for this class was generated from the following files:
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/data_structures/LiteralSet.hh
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/data_structures/LiteralSet.cc