Strong4VM: BackboneSolverAPI::Impl Class Reference
BackboneSolverAPI::Impl Class Reference
Private implementation class for BackboneSolverAPI (PIMPL idiom)
Public Member Functions
Impl ()
Default constructor - initializes all members to safe defaults.
~Impl ()
Destructor - ensures proper cleanup of all resources.
bool read_file (const string &file_name)
Reads and parses a DIMACS CNF file.
bool create_detector (const string &type)
Creates a backbone detector instance of the specified type.
vector< int > compute ()
Computes the backbone of the loaded formula.
vector< int > compute_with_assumps (const vector< int > &assumptions)
Computes conditional backbone under user-specified assumptions.
int get_max_var () const
Gets the maximum variable ID in the loaded formula.
bool get_is_sat () const
Checks if the loaded formula is satisfiable.
void print_bb () const
Prints formatted backbone summary to stdout.
Detailed Description
Private implementation class for BackboneSolverAPI (PIMPL idiom)
This class encapsulates all implementation details of the backbone solver API, providing ABI stability and compilation firewall benefits. It manages:
Components:
DIMACSReader: Parses DIMACS CNF files (including gzip-compressed .cnf.gz)
Detector instance: Polymorphic pointer to selected algorithm (one of two types)
Formula metadata: Variable count (max_id), clause vector, file path
State flags: has_file (file loaded), is_sat (satisfiability result)
Cached results: Detector instance preserves backbone computation for reuse
Lifecycle Management:
Constructor initializes all members to safe default states
Destructor ensures proper cleanup of detector and reader resources
Cleanup methods handle selective resource deallocation
Design Rationale:
Separates interface (BackboneSolverAPI) from implementation
Hides MiniSat types and detector implementations from public headers
Enables binary compatibility when internal algorithms change
Reduces compilation dependencies for API users
Note
This class is never exposed in public headers, ensuring complete encapsulation
Definition at line 191 of file BackboneSolverAPI.cc.
Constructor & Destructor Documentation
Impl()
Impl () inline
Default constructor - initializes all members to safe defaults.
Definition at line 196 of file BackboneSolverAPI.cc.
~Impl()
~Impl () inline
Destructor - ensures proper cleanup of all resources.
Definition at line 201 of file BackboneSolverAPI.cc.
Member Function Documentation
compute()
vector< int > compute () inline
Computes the backbone of the loaded formula.
Performs backbone detection on the SAT formula loaded via read_file() using the detector type selected via create_detector(). This is the core computation method of the API.
Computation Strategy:
Lazy Initialization: If detector instance doesn't exist, creates it on first call
Satisfiability Check: First verifies formula is SAT (returns empty if UNSAT)
Backbone Detection: Tests each variable v ∈ {1..max_id}:
For positive backbone: Can all models satisfy ¬v? If no, v is in backbone
For negative backbone: Can all models satisfy v? If no, ¬v is in backbone
Result Caching: Detector instance preserved for subsequent calls (idempotent)
Algorithm Details:
For each variable v:
Solve formula ∧ {¬v} to test if v can be false
Solve formula ∧ {v} to test if v can be true
If v cannot be false: v is positive backbone (always true)
If v cannot be true: ¬v is negative backbone (always false)
Return Format: Vector of signed integers representing backbone literals:
Positive integers (e.g., 5): Variable is in positive backbone (always true)
Negative integers (e.g., -12): Variable is in negative backbone (always false)
Empty vector: Either UNSAT formula, no backbone, or error occurred
Performance Considerations:
First call: O(n × SAT) where n = number of variables
Subsequent calls: O(n) - just extracts cached results
Activity bumping ("one" detector) significantly improves SAT solve times
For large formulas (>1000 vars), consider parallel approach in calling code
Example Output:
vector<int> bb = compute();
// bb = {1, -3, 5, -7}
// Interpretation:
//   Variable 1: always true (positive backbone)
//   Variable 3: always false (negative backbone)
//   Variable 5: always true (positive backbone)
//   Variable 7: always false (negative backbone)
//   Variables 2,4,6,8,...: not in backbone (can be true or false)
Returns
Vector of backbone literals (positive/negative integers), empty if UNSAT or error
Note
Returns empty vector if no file loaded or no detector type selected
First call creates detector instance (expensive), subsequent calls reuse it
Sets is_sat flag based on satisfiability check result
Exception-safe: catches all exceptions and returns empty vector
Detector instance remains allocated for reuse - call cleanup_detector() to free
See also
compute_with_assumps() for conditional backbone under assumptions
is_satisfiable() to check SAT/UNSAT status after computation
print_backbone() for formatted output of results
Definition at line 391 of file BackboneSolverAPI.cc.
References CheckCandidatesOneByOne::backbone_sign(), CheckCandidatesOneByOneWithoutAttention::backbone_sign(), CheckCandidatesOneByOne::initialize(), CheckCandidatesOneByOneWithoutAttention::initialize(), CheckCandidatesOneByOne::is_backbone(), CheckCandidatesOneByOneWithoutAttention::is_backbone(), CheckCandidatesOneByOne::run(), and CheckCandidatesOneByOneWithoutAttention::run().
Referenced by BackboneSolverAPI::compute_backbone().
compute_with_assumps()
vector< int > compute_with_assumps (const vector< int > & assumptions) inline
Computes conditional backbone under user-specified assumptions.
Computes the backbone of the formula when certain variables are fixed to specific values. This enables analysis of conditional dependencies: "If feature X is selected and feature Y is excluded, which features become mandatory/forbidden?"
Assumptions as Constraints: Assumptions are treated as additional unit clauses added to the formula:
Assumption {5} means: Add clause (5) to formula → variable 5 must be true
Assumption {-12} means: Add clause (-12) to formula → variable 12 must be false
Formula becomes: Original_CNF ∧ assumptions
Use Cases:
Feature model configuration: "If I select feature A, what else must be selected?"
What-if analysis: "What are the consequences of enabling this option?"
Partial configuration: "Given user choices X, Y, what is determined?"
Incremental refinement: Iteratively add assumptions to explore configuration space
Algorithm Behavior:
Creates fresh detector instance (does NOT reuse cached detector)
Initializes SAT solver with formula + assumptions
Performs full backbone detection under constrained formula
Cleans up detector after extraction (no caching for assumption-based calls)
Return Values:
Non-empty vector: Backbone literals under assumptions (formula ∧ assumptions is SAT)
Empty vector: Either (1) UNSAT under assumptions, or (2) error occurred
UNSAT Handling: If assumptions make the formula unsatisfiable, returns empty vector. Check return value size to distinguish:
vector<int> bb = compute_with_assumps({5, -12});
if (bb.empty()) {
    // Either UNSAT or no backbone under assumptions
    // Cannot determine satisfiability from this method alone
}
Example Usage:
// Feature model: variables 1-10 represent features
BackboneSolverAPI solver;
solver.read_dimacs("feature_model.cnf");
solver.create_backbone_detector("one");
// What if feature 3 is selected and feature 7 is excluded?
vector<int> assumptions = {3, -7};
vector<int> conditional_bb = solver.compute_backbone_with_assumptions(assumptions);
// conditional_bb might be {1, 3, -5, -7, 9}
// Interpretation: Under assumptions {3, -7}:
//   Features 1, 3, 9 are mandatory (positive backbone)
//   Features 5, 7 are forbidden (negative backbone)
//   Other features are optional
Comparison with compute():
Aspect compute() compute_with_assumps()
Assumptions None (base formula) User-specified constraints
Detector caching Cached after first call Fresh detector each call
Performance Fast (reuses detector) Slower (recreates detector)
Use case Global backbone Conditional backbone
Parameters
assumptions Vector of assumption literals (e.g., {5, -12, 3})
Returns
Vector of backbone literals under assumptions, empty if UNSAT or error
Note
Does NOT reuse cached detector - creates fresh instance each call
Does NOT update is_sat flag (unlike compute())
Detector is deallocated after extraction (no caching)
Assumptions are in DIMACS format: positive=true, negative=false
Exception-safe: catches all exceptions and returns empty vector
Cannot distinguish between UNSAT and empty backbone from return value alone
See also
compute() for unconditional backbone computation
Definition at line 555 of file BackboneSolverAPI.cc.
References CheckCandidatesOneByOne::backbone_sign(), CheckCandidatesOneByOneWithoutAttention::backbone_sign(), CheckCandidatesOneByOne::is_backbone(), CheckCandidatesOneByOneWithoutAttention::is_backbone(), CheckCandidatesOneByOne::run_with_assumptions(), and CheckCandidatesOneByOneWithoutAttention::run_with_assumptions().
Referenced by BackboneSolverAPI::compute_backbone_with_assumptions().
create_detector()
bool create_detector (const string & type) inline
Creates a backbone detector instance of the specified type.
Selects and configures the backbone detection algorithm to use for subsequent compute() calls. This method only stores the detector type - the actual detector instance is lazily created during the first compute() call.
Supported Detector Types:
**"one"** or **"simple"**: CheckCandidatesOneByOne
Uses SAT solver activity bumping for guided search
Bumps variables during testing to improve solver heuristics
Generally faster and recommended for most use cases
Default algorithm used by dimacs2graphs pipeline
**"without"** or **"withoutattention"**: CheckCandidatesOneByOneWithoutAttention
No activity bumping during backbone detection
Standard SAT solver behavior without search guidance
Useful as baseline for performance comparisons
Algorithm Selection Guidelines:
For production use: "one" (default, best performance)
For benchmarking: "without" (baseline comparison)
Both algorithms produce identical backbone results
Only difference is search strategy and performance
Parameters
type Detector type string ("one", "simple", "without", or "withoutattention")
Returns
true if detector type is valid and file was previously loaded, false otherwise
Note
Requires prior call to read_file() - returns false if no file loaded
Cleans up any existing detector instance before setting new type
Type string matching is case-sensitive
Actual detector instantiation is deferred until compute() call (lazy initialization)
See also
CheckCandidatesOneByOne for "one"/"simple" implementation
CheckCandidatesOneByOneWithoutAttention for "without"/"withoutattention" implementation
Definition at line 313 of file BackboneSolverAPI.cc.
Referenced by BackboneSolverAPI::create_backbone_detector().
get_is_sat()
bool get_is_sat () const inline
Checks if the loaded formula is satisfiable.
Returns
true if formula is SAT (determined during compute()), false otherwise
Note
Only valid after calling compute() - returns false before computation
Definition at line 633 of file BackboneSolverAPI.cc.
Referenced by BackboneSolverAPI::is_satisfiable().
get_max_var()
int get_max_var () const inline
Gets the maximum variable ID in the loaded formula.
Returns
Maximum variable ID (number of variables), or 0 if no file loaded
Definition at line 625 of file BackboneSolverAPI.cc.
Referenced by BackboneSolverAPI::get_max_variable().
print_bb()
void print_bb () const inline
Prints formatted backbone summary to stdout.
Outputs a human-readable summary of the backbone computation including:
Formula statistics (number of variables and clauses)
Satisfiability status (SAT/UNSAT)
Backbone size and percentage of determined variables
List of all backbone literals
Output Format Example:
Formula statistics:
  Variables: 100
  Clauses: 450
Formula is SATISFIABLE
Backbone size: 23 literals (23.00% of variables)
Backbone literals: 1 -3 5 7 -9 11 -15 18 ...
Special Cases:
UNSAT formula: Prints "Formula is UNSATISFIABLE"
No computation yet: Prints "No backbone computed yet"
Empty backbone: Shows size 0 with no literals listed
Note
Requires prior successful compute() call to show results
Output written to std::cout
Positive literals indicate positive backbone, negative indicate negative backbone
Definition at line 663 of file BackboneSolverAPI.cc.
References CheckCandidatesOneByOne::backbone_sign(), CheckCandidatesOneByOneWithoutAttention::backbone_sign(), CheckCandidatesOneByOne::is_backbone(), and CheckCandidatesOneByOneWithoutAttention::is_backbone().
Referenced by BackboneSolverAPI::print_backbone().
read_file()
bool read_file (const string & file_name) inline
Reads and parses a DIMACS CNF file.
Loads a SAT formula from a DIMACS CNF file, supporting both plain text (.cnf) and gzip-compressed (.cnf.gz) formats. This method:
Cleans up any existing detector and reader instances
Opens the file using zlib (transparent gzip decompression)
Parses CNF using DIMACSReader
Stores formula metadata (variables, clauses)
Resets satisfiability state
File Format: Standard DIMACS CNF format:
p cnf <num_variables> <num_clauses>
<clause1>
<clause2>
...
Example:
p cnf 4 3
1 2 0
-1 3 0
-2 -3 4 0
Gzip Support: Automatically detects and decompresses .gz files via zlib's gzopen. No special handling needed - just pass the .cnf.gz filename.
Parameters
file_name Path to DIMACS CNF file (.cnf or .cnf.gz)
Returns
true if file was successfully read and parsed, false otherwise
Note
Clears any previously loaded formula and computed backbone
Exception-safe: catches all exceptions and returns false
Sets has_file=true and is_sat=false on success
See also
DIMACSReader for parsing details
Definition at line 247 of file BackboneSolverAPI.cc.
References DIMACSReader::get_clause_vector(), DIMACSReader::get_max_id(), and DIMACSReader::read().
Referenced by BackboneSolverAPI::read_dimacs().
The documentation for this class was generated from the following file:
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/api/BackboneSolverAPI.cc