Strong4VM: BackboneSolverAPI Class Reference
BackboneSolverAPI Class Reference
BackboneSolver API
Main API class for backbone computation using PIMPL pattern.
#include <BackboneSolverAPI.hh>
Classes
class Impl
Private implementation class for BackboneSolverAPI (PIMPL idiom)
Public Member Functions
BackboneSolverAPI ()
Construct a new BackboneSolverAPI object.
~BackboneSolverAPI ()
Destroy the BackboneSolverAPI object.
bool read_dimacs (const string &file_name)
Read a DIMACS CNF file.
bool create_backbone_detector (const string &bb_detector="simple")
Create a backbone detector for the last read DIMACS file.
vector< int > compute_backbone ()
Compute the backbone using the created detector.
vector< int > compute_backbone_with_assumptions (const vector< int > &assumptions)
Compute backbone with assumptions.
int get_max_variable () const
Get the maximum variable ID from the last read file.
bool is_satisfiable () const
Check if the last read formula is satisfiable.
void print_backbone () const
Print the backbone to standard output.
Detailed Description
Main API class for backbone computation using PIMPL pattern.
This class provides a high-level interface for computing backbones of Boolean formulas. It uses the PIMPL (Pointer to Implementation) pattern to hide implementation details and provide a stable ABI.
Typical workflow:
Create a BackboneSolverAPI instance
Call read_dimacs() to load a CNF formula
Call create_backbone_detector() to choose an algorithm
Call compute_backbone() to get the result
Example:
BackboneSolverAPI api;
api.read_dimacs("formula.cnf");
api.create_backbone_detector("one");
vector<int> backbone = api.compute_backbone();
Definition at line 128 of file BackboneSolverAPI.hh.
Constructor & Destructor Documentation
BackboneSolverAPI()
BackboneSolverAPI ()
Construct a new BackboneSolverAPI object.
Constructs a new BackboneSolverAPI instance.
Initializes the PIMPL implementation object with default state.
Definition at line 790 of file BackboneSolverAPI.cc.
~BackboneSolverAPI()
~BackboneSolverAPI ()
Destroy the BackboneSolverAPI object.
Destructor - cleans up PIMPL implementation.
Deallocates the implementation object, which triggers cleanup of detector and reader resources.
Definition at line 798 of file BackboneSolverAPI.cc.
Member Function Documentation
compute_backbone()
vector< int > compute_backbone ()
Compute the backbone using the created detector.
Public API wrapper for compute()
Runs the backbone detection algorithm and returns the result. Must be called after create_backbone_detector().
Returns
vector<int> Vector of backbone literals:
Positive values indicate variables that must be true
Negative values indicate variables that must be false
Empty vector if no file read, no detector created, or formula is unsatisfiable
Vector of backbone literals
Definition at line 827 of file BackboneSolverAPI.cc.
References BackboneSolverAPI::Impl::compute().
Referenced by Dimacs2GraphsAPI::Impl::generate_graphs_impl(), and main().
compute_backbone_with_assumptions()
vector< int > compute_backbone_with_assumptions (const vector< int > & assumptions)
Compute backbone with assumptions.
Public API wrapper for compute_with_assumps()
Computes the backbone of the formula under given assumptions. Assumptions are literals that are forced to be true during solving. Must be called after create_backbone_detector().
Parameters
assumptions Vector of literal assumptions:
Positive int: variable must be true (e.g., 5 means x5=true)
Negative int: variable must be false (e.g., -3 means x3=false)
Returns
vector<int> Vector of backbone literals under these assumptions (same format as compute_backbone()) Empty vector if unsatisfiable under assumptions
Delegates to internal PIMPL implementation. See BackboneSolverAPI.hh for detailed parameter documentation.
Definition at line 837 of file BackboneSolverAPI.cc.
References BackboneSolverAPI::Impl::compute_with_assumps().
Referenced by Dimacs2GraphsAPI::Impl::generate_graphs_impl(), and Dimacs2GraphsAPI::Impl::ThreadWorker::process_variable().
create_backbone_detector()
bool create_backbone_detector (const string & bb_detector = "simple")
Create a backbone detector for the last read DIMACS file.
Public API wrapper for create_detector()
Creates and initializes a backbone detection algorithm. Must be called after read_dimacs().
Parameters
bb_detector Algorithm to use:
"one" or "simple": CheckCandidatesOneByOne (fast upper-bound, default)
"without" or "withoutattention": CheckCandidatesOneByOneWithoutAttention (baseline)
Returns
true if detector was successfully created
false if no DIMACS file has been read or bb_detector is invalid
Delegates to internal PIMPL implementation. See BackboneSolverAPI.hh for detailed parameter documentation.
Definition at line 818 of file BackboneSolverAPI.cc.
References BackboneSolverAPI::Impl::create_detector().
Referenced by Dimacs2GraphsAPI::Impl::generate_graphs_impl(), and main().
get_max_variable()
int get_max_variable () const
Get the maximum variable ID from the last read file.
Public API wrapper for get_max_var()
Returns
int The highest variable number in the CNF formula
Maximum variable ID
Definition at line 846 of file BackboneSolverAPI.cc.
References BackboneSolverAPI::Impl::get_max_var().
Referenced by Dimacs2GraphsAPI::Impl::generate_graphs_impl(), and main().
is_satisfiable()
bool is_satisfiable () const
Check if the last read formula is satisfiable.
Public API wrapper for get_is_sat()
This can only be called after compute_backbone() has been executed.
Returns
true if the formula has at least one satisfying assignment
false if the formula is unsatisfiable
true if formula is SAT, false otherwise
Definition at line 855 of file BackboneSolverAPI.cc.
References BackboneSolverAPI::Impl::get_is_sat().
print_backbone()
void print_backbone () const
Print the backbone to standard output.
Public API wrapper for print_bb()
Outputs the computed backbone in human-readable format. Prints "UNSATISFIABLE" if formula is not satisfiable. Otherwise prints backbone size and the list of backbone literals.
Definition at line 862 of file BackboneSolverAPI.cc.
References BackboneSolverAPI::Impl::print_bb().
Referenced by main().
read_dimacs()
bool read_dimacs (const string & file_name)
Read a DIMACS CNF file.
Public API wrapper for read_file()
Parses a CNF formula from a file in DIMACS format. The file must follow the standard DIMACS CNF specification.
Parameters
file_name Path to the DIMACS CNF file
Returns
true if file is valid and successfully read
false if file cannot be opened or has invalid format
Delegates to internal PIMPL implementation. See BackboneSolverAPI.hh for detailed parameter documentation.
Definition at line 808 of file BackboneSolverAPI.cc.
References BackboneSolverAPI::Impl::read_file().
Referenced by Dimacs2GraphsAPI::Impl::generate_graphs_impl(), and main().
The documentation for this class was generated from the following files:
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/api/BackboneSolverAPI.hh
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/api/BackboneSolverAPI.cc