Strong4VM: LiteralSet Class Reference
LiteralSet Class Reference
Efficient bit-set for storing MiniSat literals.
#include <LiteralSet.hh>
Public Types
typedef const_LiteralSetIterator const_iterator
Standard const iterator type for range-based for loops.
Public Member Functions
LiteralSet ()
Construct an empty LiteralSet.
bool add (Lit l)
Add a literal to the set.
bool remove (Lit l)
Remove a literal from the set.
bool get (Lit l) const
Check if a literal is in the set.
void clear ()
Clear all literals from the set.
template<typename ModelVec >
void discard_from_model (const ModelVec &model, int max_var, vec< Lit > &discarded)
Ultra-fast bulk removal based on solver model.
size_t size () const
Get the number of literals in the set.
const_infinite_LiteralSetIterator infinite_iterator () const
Create an infinite iterator that cycles through the set.
size_t physical_size () const
Get the physical size of internal storage.
const_iterator begin () const
Get iterator to first literal.
const_iterator end () const
Get iterator past last literal.
Detailed Description
Efficient bit-set for storing MiniSat literals.
A high-performance data structure for storing sets of literals. Uses vector<uint8_t> instead of vector<bool> for much better performance. Provides O(1) add, remove, and membership testing operations.
The internal representation uses one byte per possible literal index, where each byte is either 0 (not present) or 1 (present).
Example usage:
LiteralSet candidates;
candidates.add(mkLit(5, false));  // Add positive literal for variable 5
candidates.add(mkLit(7, true));   // Add negative literal for variable 7
if (candidates.get(mkLit(5, false))) {
    // Literal is in the set
}
candidates.remove(mkLit(5, false));
Definition at line 163 of file LiteralSet.hh.
Member Typedef Documentation
const_iterator
typedef const_LiteralSetIterator const_iterator
Standard const iterator type for range-based for loops.
Definition at line 166 of file LiteralSet.hh.
Constructor & Destructor Documentation
LiteralSet()
LiteralSet () inline
Construct an empty LiteralSet.
Definition at line 171 of file LiteralSet.hh.
Member Function Documentation
add()
bool add (Lit l) inline
Add a literal to the set.
Parameters
l Literal to add
Returns
true if literal was added (wasn't already present)
false if literal was already in the set
Definition at line 257 of file LiteralSet.hh.
Referenced by CheckCandidatesOneByOne::initialize(), CheckCandidatesOneByOneWithoutAttention::initialize(), CheckCandidatesOneByOne::run(), CheckCandidatesOneByOneWithoutAttention::run(), CheckCandidatesOneByOne::run_with_assumptions(), and CheckCandidatesOneByOneWithoutAttention::run_with_assumptions().
begin()
LiteralSet::const_iterator begin () const inline
Get iterator to first literal.
Returns
const_iterator to beginning
Definition at line 320 of file LiteralSet.hh.
clear()
void clear () inline
Clear all literals from the set.
Definition at line 281 of file LiteralSet.hh.
Referenced by CheckCandidatesOneByOne::run_with_assumptions(), and CheckCandidatesOneByOneWithoutAttention::run_with_assumptions().
discard_from_model()
template<typename ModelVec > void discard_from_model (const ModelVec & model, int max_var, vec< Lit > & discarded) inline
Ultra-fast bulk removal based on solver model.
Removes all candidate literals that are contradicted by the given satisfying assignment. Uses manual loop unrolling and branch hints for maximum performance.
Template Parameters
ModelVec Type of model vector (must support operator[] and size())
Parameters
model Satisfying assignment from solver
max_var Maximum variable ID to process
discarded Output vector for removed literals
Definition at line 326 of file LiteralSet.hh.
References end().
Referenced by CheckCandidatesOneByOneWithoutAttention::run(), CheckCandidatesOneByOne::run_with_assumptions(), and CheckCandidatesOneByOneWithoutAttention::run_with_assumptions().
end()
LiteralSet::const_iterator end () const inline
Get iterator past last literal.
Returns
const_iterator to end
Definition at line 317 of file LiteralSet.hh.
References physical_size().
Referenced by discard_from_model().
get()
bool get (Lit l) const inline
Check if a literal is in the set.
Parameters
l Literal to check
Returns
true if literal is present in the set
false otherwise
Definition at line 275 of file LiteralSet.hh.
Referenced by const_infinite_LiteralSetIterator::const_infinite_LiteralSetIterator(), const_LiteralSetIterator::const_LiteralSetIterator(), CheckCandidatesOneByOne::is_backbone(), CheckCandidatesOneByOneWithoutAttention::is_backbone(), const_infinite_LiteralSetIterator::operator*(), const_LiteralSetIterator::operator*(), const_infinite_LiteralSetIterator::operator++(), and const_LiteralSetIterator::operator++().
infinite_iterator()
const_infinite_LiteralSetIterator infinite_iterator () const inline
Create an infinite iterator that cycles through the set.
Returns
Infinite iterator starting at the beginning
Definition at line 228 of file LiteralSet.hh.
Referenced by CheckCandidatesOneByOne::run_with_assumptions(), and CheckCandidatesOneByOneWithoutAttention::run_with_assumptions().
physical_size()
size_t physical_size () const inline
Get the physical size of internal storage.
Returns
Size of internal vector (>= logical size)
Definition at line 236 of file LiteralSet.hh.
Referenced by const_infinite_LiteralSetIterator::const_infinite_LiteralSetIterator(), const_LiteralSetIterator::const_LiteralSetIterator(), end(), const_infinite_LiteralSetIterator::operator++(), and const_LiteralSetIterator::operator++().
remove()
bool remove (Lit l) inline
Remove a literal from the set.
Parameters
l Literal to remove
Returns
true if literal was removed (was present)
false if literal was not in the set
Definition at line 266 of file LiteralSet.hh.
Referenced by CheckCandidatesOneByOneWithoutAttention::run(), CheckCandidatesOneByOne::run_with_assumptions(), and CheckCandidatesOneByOneWithoutAttention::run_with_assumptions().
size()
size_t size () const inline
Get the number of literals in the set.
Returns
Number of literals currently stored
Definition at line 222 of file LiteralSet.hh.
Referenced by const_infinite_LiteralSetIterator::const_infinite_LiteralSetIterator(), const_infinite_LiteralSetIterator::operator++(), CheckCandidatesOneByOne::run(), CheckCandidatesOneByOneWithoutAttention::run(), CheckCandidatesOneByOne::run_with_assumptions(), and CheckCandidatesOneByOneWithoutAttention::run_with_assumptions().
The documentation for this class was generated from the following file:
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/data_structures/LiteralSet.hh