Strong4VM: Strong4VMAPI::Impl Class Reference
Strong4VMAPI::Impl Class Reference
Internal implementation class (PIMPL idiom)
Public Member Functions
Impl ()
InputType detect_file_type (const std::string &filename) const
Detect file type based on file extension.
std::string get_basename (const std::string &filepath) const
Extract basename from file path without extension.
std::string get_directory (const std::string &filepath) const
Extract directory path from file path.
std::string validate_configuration (const AnalysisConfig &config) const
Validate analysis configuration before execution.
std::string detector_to_string (BackboneDetector detector) const
Convert detector enum to string identifier.
AnalysisResult perform_analysis (const AnalysisConfig &config)
Execute the complete Strong4VM analysis pipeline.
Public Attributes
bool verbose
ConversionMode default_conversion_mode
BackboneDetector default_detector
int default_num_threads
AnalysisResult last_result
Detailed Description
Internal implementation class (PIMPL idiom)
This class encapsulates all implementation details of the Strong4VM API:
Configuration state: Default settings for conversion mode, detector, threads, verbosity
Pipeline orchestration: Coordinates uvl2dimacs and dimacs2graphs execution
File management: Handles paths, extensions, temporary files
Validation logic: Ensures configuration parameters are valid before execution
Result aggregation: Combines statistics from both pipeline stages
The PIMPL pattern ensures that changes to these internal details do not affect the binary interface of the public Strong4VMAPI class.
Definition at line 73 of file Strong4VMAPI.cc.
Constructor & Destructor Documentation
Impl()
Impl () inline
Definition at line 84 of file Strong4VMAPI.cc.
Member Function Documentation
detect_file_type()
InputType detect_file_type (const std::string & filename) const inline
Detect file type based on file extension.
Performs case-insensitive extension matching to determine input type:
.uvl → InputType::UVL (feature model file)
.dimacs or .cnf → InputType::DIMACS (CNF formula file)
Other extensions → InputType::AUTO (unknown, requires manual specification)
Parameters
filename Path to the input file (can be relative or absolute)
Returns
Detected InputType enum value
Definition at line 101 of file Strong4VMAPI.cc.
References strong4vm::AUTO, strong4vm::DIMACS, and strong4vm::UVL.
Referenced by Strong4VMAPI::Impl::perform_analysis(), and Strong4VMAPI::Impl::validate_configuration().
detector_to_string()
std::string detector_to_string (BackboneDetector detector) const inline
Convert detector enum to string identifier.
Translates BackboneDetector enum values to string identifiers used by the dimacs2graphs API:
BackboneDetector::ONE → "one" (with activity bumping, faster)
BackboneDetector::WITHOUT → "without" (without activity bumping, baseline)
Parameters
detector Detector enum value
Returns
String identifier for dimacs2graphs API
Definition at line 218 of file Strong4VMAPI.cc.
References strong4vm::FLATLAND, and strong4vm::RUSH.
Referenced by Strong4VMAPI::Impl::perform_analysis().
get_basename()
std::string get_basename (const std::string & filepath) const inline
Extract basename from file path without extension.
Uses filesystem::path::stem() to extract the filename without directory components or file extension. Used for generating output filenames.
Examples:
"/path/to/model.uvl" → "model"
"example.dimacs" → "example"
"../test/file.cnf" → "file"
Parameters
filepath Full path to file
Returns
Basename without directory path or extension
Definition at line 132 of file Strong4VMAPI.cc.
Referenced by Strong4VMAPI::Impl::perform_analysis().
get_directory()
std::string get_directory (const std::string & filepath) const inline
Extract directory path from file path.
Returns the parent directory of the file. If the file path has no directory component, returns "." (current directory).
Parameters
filepath Full path to file
Returns
Parent directory path, or "." if no parent
Definition at line 146 of file Strong4VMAPI.cc.
Referenced by Strong4VMAPI::Impl::perform_analysis().
perform_analysis()
AnalysisResult perform_analysis (const AnalysisConfig & config) inline
Execute the complete Strong4VM analysis pipeline.
This is the core implementation method that orchestrates the entire pipeline:
Pipeline Stages
Stage 0: Validation
Validate all configuration parameters
Detect input file type if AUTO
Ensure output directory exists or can be created
Stage 1: UVL to DIMACS Conversion (if input is UVL)
Use uvl2dimacs API to parse and convert feature model
Apply selected CNF transformation mode
Generate DIMACS file in output directory
Mark as temporary if keep_dimacs is false
Stage 2: DIMACS to Graphs
Use dimacs2graphs API for backbone detection
Generate requires/excludes graphs using parallel processing
Identify core and dead features from global backbone
Write Pajek .net files and feature lists
Stage 3: Cleanup
Remove temporary DIMACS file if needed
Aggregate statistics from both stages
Return comprehensive analysis result
Error Handling
Errors at any stage cause immediate pipeline termination with:
success = false
Descriptive error message indicating which stage failed
Automatic cleanup of temporary files
Parameters
config Analysis configuration with all pipeline parameters
Returns
AnalysisResult containing success status, statistics, file paths, and errors
Definition at line 263 of file Strong4VMAPI.cc.
References strong4vm::AUTO, AnalysisConfig::conversion_mode, UVL2Dimacs::convert(), AnalysisResult::core_features, AnalysisResult::core_features_file, AnalysisResult::dead_features, AnalysisResult::dead_features_file, Strong4VMAPI::Impl::detect_file_type(), AnalysisConfig::detector, Strong4VMAPI::Impl::detector_to_string(), strong4vm::DIMACS, AnalysisResult::dimacs_file, AnalysisResult::error_message, AnalysisResult::excludes_graph_file, Dimacs2GraphsAPI::generate_graphs(), Strong4VMAPI::Impl::get_basename(), Strong4VMAPI::Impl::get_directory(), Dimacs2GraphsAPI::get_error_message(), Dimacs2GraphsAPI::get_global_backbone(), Dimacs2GraphsAPI::get_num_clauses(), Dimacs2GraphsAPI::get_num_variables(), AnalysisResult::global_backbone, AnalysisConfig::input_file, AnalysisResult::input_file, AnalysisConfig::input_type, AnalysisResult::input_type, AnalysisConfig::keep_dimacs, AnalysisResult::num_clauses, AnalysisResult::num_constraints, AnalysisResult::num_features, AnalysisResult::num_relations, AnalysisResult::num_skipped_constraints, AnalysisConfig::num_threads, AnalysisResult::num_variables, AnalysisConfig::output_dir, AnalysisResult::requires_graph_file, UVL2Dimacs::set_backbone_simplification(), UVL2Dimacs::set_mode(), UVL2Dimacs::set_verbose(), uvl2dimacs::STRAIGHTFORWARD, AnalysisResult::success, strong4vm::TSEITIN, uvl2dimacs::TSEITIN, strong4vm::UVL, Strong4VMAPI::Impl::validate_configuration(), and Strong4VMAPI::Impl::verbose.
validate_configuration()
std::string validate_configuration (const AnalysisConfig & config) const inline
Validate analysis configuration before execution.
Performs comprehensive validation of configuration parameters:
Input file checks: Exists, non-empty path
File type detection: Can determine UVL or DIMACS if AUTO
Thread count validation: At least 1 thread specified
Output directory: Exists or can be created
This validation happens before any pipeline execution to ensure fast-fail behavior and clear error messages.
Parameters
config Configuration to validate
Returns
Empty string if valid, descriptive error message if invalid
Definition at line 169 of file Strong4VMAPI.cc.
References strong4vm::AUTO, Strong4VMAPI::Impl::detect_file_type(), AnalysisConfig::input_file, AnalysisConfig::input_type, AnalysisConfig::num_threads, and AnalysisConfig::output_dir.
Referenced by Strong4VMAPI::Impl::perform_analysis().
Member Data Documentation
default_conversion_mode
ConversionMode default_conversion_mode
Definition at line 77 of file Strong4VMAPI.cc.
default_detector
BackboneDetector default_detector
Definition at line 78 of file Strong4VMAPI.cc.
default_num_threads
int default_num_threads
Definition at line 79 of file Strong4VMAPI.cc.
last_result
AnalysisResult last_result
Definition at line 82 of file Strong4VMAPI.cc.
verbose
bool verbose
Definition at line 76 of file Strong4VMAPI.cc.
Referenced by Strong4VMAPI::Impl::perform_analysis().
The documentation for this class was generated from the following file:
/mnt/c/improving_strong4vm/strong4vm/api/src/Strong4VMAPI.cc