Strong4VM: DIMACSReader Class Reference
DIMACSReader Class Reference
Parser for DIMACS CNF format files.
#include <DIMACSReader.hh>
Public Member Functions
DIMACSReader (Reader &input_file)
Construct DIMACS reader from a Reader.
DIMACSReader (const DIMACSReader &orig)
Copy constructor.
virtual ~DIMACSReader ()
Destructor.
void read ()
Parse the DIMACS file.
Var get_max_id () const
Get maximum variable ID in the formula.
const CNF & get_clause_vector () const
Get the parsed CNF formula.
Detailed Description
Parser for DIMACS CNF format files.
Parses Boolean formulas in the standard DIMACS CNF format. The format consists of:
Comment lines starting with 'c'
Problem line: p cnf [num_vars] [num_clauses]
Clause lines: space-separated literals terminated by 0
Example DIMACS file:
c This is a comment
p cnf 3 2
1 -2 0
2 3 0
Usage:
Reader reader(input_stream);
DIMACSReader dimacs(reader);
dimacs.read();
const CNF& clauses = dimacs.get_clause_vector();
Var max_var = dimacs.get_max_id();
Definition at line 371 of file DIMACSReader.hh.
Constructor & Destructor Documentation
DIMACSReader() [1/2]
DIMACSReader (Reader & input_file)
Construct DIMACS reader from a Reader.
Parameters
input_file Reader providing character input
Definition at line 76 of file DIMACSReader.cc.
DIMACSReader() [2/2]
DIMACSReader (const DIMACSReader & orig)
Copy constructor.
Parameters
orig DIMACSReader to copy from
Definition at line 78 of file DIMACSReader.cc.
~DIMACSReader()
~DIMACSReader () virtual
Destructor.
Definition at line 83 of file DIMACSReader.cc.
Member Function Documentation
get_clause_vector()
const CNF & get_clause_vector () const inline
Get the parsed CNF formula.
Returns
Vector of clauses (each clause is a LitSet)
Definition at line 408 of file DIMACSReader.hh.
Referenced by BackboneSolverAPI::Impl::read_file().
get_max_id()
Var get_max_id () const inline
Get maximum variable ID in the formula.
Returns
Highest variable number used
Definition at line 402 of file DIMACSReader.hh.
Referenced by BackboneSolverAPI::Impl::read_file().
read()
void read ()
Parse the DIMACS file.
Reads and parses the entire DIMACS CNF file, storing clauses internally. Throws DIMACSReaderException on parse errors.
Definition at line 100 of file DIMACSReader.cc.
References Reader::skip_whitespace(), and skipLine().
Referenced by BackboneSolverAPI::Impl::read_file().
The documentation for this class was generated from the following files:
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/io/DIMACSReader.hh
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/io/DIMACSReader.cc