Strong4VM: const_infinite_LiteralSetIterator Class Reference
const_infinite_LiteralSetIterator Class Reference
Infinite iterator that cycles through literals in a LiteralSet.
#include <LiteralSet.hh>
Public Member Functions
const_infinite_LiteralSetIterator (const LiteralSet &ls, size_t x)
Construct an infinite iterator.
const_infinite_LiteralSetIterator (const const_infinite_LiteralSetIterator &mit)
Copy constructor.
const_infinite_LiteralSetIterator & operator++ ()
Advance to next literal (wraps around at end)
const Lit operator* () const
Dereference to get current literal.
bool operator== (const const_infinite_LiteralSetIterator &rhs)
Equality comparison.
bool operator!= (const const_infinite_LiteralSetIterator &rhs)
Inequality comparison.
Detailed Description
Infinite iterator that cycles through literals in a LiteralSet.
This iterator wraps around when it reaches the end of the set, making it useful for round-robin processing of backbone candidates.
Definition at line 26 of file LiteralSet.hh.
Constructor & Destructor Documentation
const_infinite_LiteralSetIterator() [1/2]
const_infinite_LiteralSetIterator (const LiteralSet & ls, size_t x)
Construct an infinite iterator.
Parameters
ls The LiteralSet to iterate over
x Starting position (index in internal storage)
Definition at line 8 of file LiteralSet.cc.
References LiteralSet::get(), LiteralSet::physical_size(), and LiteralSet::size().
const_infinite_LiteralSetIterator() [2/2]
const_infinite_LiteralSetIterator (const const_infinite_LiteralSetIterator & mit) inline
Copy constructor.
Parameters
mit Iterator to copy from
Definition at line 39 of file LiteralSet.hh.
Member Function Documentation
operator!=()
bool operator!= (const const_infinite_LiteralSetIterator & rhs) inline
Inequality comparison.
Parameters
rhs Iterator to compare with
Returns
true if iterators point to different positions
Definition at line 70 of file LiteralSet.hh.
operator*()
const Lit operator* () const inline
Dereference to get current literal.
Returns
The current literal
Definition at line 298 of file LiteralSet.hh.
References LiteralSet::get().
operator++()
const_infinite_LiteralSetIterator & operator++ () inline
Advance to next literal (wraps around at end)
Returns
Reference to this iterator
Definition at line 287 of file LiteralSet.hh.
References LiteralSet::get(), LiteralSet::physical_size(), and LiteralSet::size().
operator==()
bool operator== (const const_infinite_LiteralSetIterator & rhs) inline
Equality comparison.
Parameters
rhs Iterator to compare with
Returns
true if iterators point to same position
Definition at line 60 of file LiteralSet.hh.
The documentation for this class was generated from the following files:
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/data_structures/LiteralSet.hh
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/data_structures/LiteralSet.cc