Strong4VM: CheckCandidatesOneByOneWithoutAttention Class Reference
CheckCandidatesOneByOneWithoutAttention Class Reference
Backbone Detection Algorithms
Upper-bound backbone detector without activity bumping.
#include <CheckCandidatesOneByOneWithoutAttention.hh>
Public Member Functions
CheckCandidatesOneByOneWithoutAttention (Var max_id, const CNF &clauses)
Construct detector for a CNF formula.
virtual ~CheckCandidatesOneByOneWithoutAttention () override
Destructor.
virtual bool initialize () override
Initialize and check satisfiability.
virtual void run () override
Run backbone detection without activity bumping.
virtual bool run_with_assumptions (const vec< Lit > &assumptions) override
Run backbone detection with assumptions.
virtual bool is_backbone (const Lit &literal) const override
Check if literal is in backbone.
virtual bool is_backbone (Var var) const override
Check if variable is in backbone.
virtual bool backbone_sign (Var var) const override
Get sign of backbone variable.
Public Member Functions inherited from BackBone
virtual ~BackBone ()
Virtual destructor for proper cleanup of derived classes.
Detailed Description
Upper-bound backbone detector without activity bumping.
Similar to CheckCandidatesOneByOne but without activity bumping. This variant relies entirely on the SAT solver's default variable selection heuristics rather than guiding it toward specific assignments.
Generally slower than the attention-based version since the solver is not guided toward finding alternative assignments that contradict backbone candidates.
Useful for comparison and baseline measurements.
Definition at line 40 of file CheckCandidatesOneByOneWithoutAttention.hh.
Constructor & Destructor Documentation
CheckCandidatesOneByOneWithoutAttention()
CheckCandidatesOneByOneWithoutAttention (Var max_id, const CNF & clauses)
Construct detector for a CNF formula.
Parameters
max_id Maximum variable ID
clauses CNF formula
Definition at line 57 of file CheckCandidatesOneByOneWithoutAttention.cc.
~CheckCandidatesOneByOneWithoutAttention()
~CheckCandidatesOneByOneWithoutAttention () override virtual
Destructor.
Definition at line 63 of file CheckCandidatesOneByOneWithoutAttention.cc.
Member Function Documentation
backbone_sign()
bool backbone_sign (Var var) const override virtual
Get sign of backbone variable.
Parameters
var Backbone variable
Returns
true if positive, false if negative
Implements BackBone.
Definition at line 210 of file CheckCandidatesOneByOneWithoutAttention.cc.
References CheckCandidatesOneByOneWithoutAttention::is_backbone().
Referenced by BackboneSolverAPI::Impl::compute(), BackboneSolverAPI::Impl::compute_with_assumps(), and BackboneSolverAPI::Impl::print_bb().
initialize()
bool initialize () override virtual
Initialize and check satisfiability.
Returns
true if satisfiable
Implements BackBone.
Definition at line 66 of file CheckCandidatesOneByOneWithoutAttention.cc.
References LiteralSet::add().
Referenced by BackboneSolverAPI::Impl::compute().
is_backbone() [1/2]
bool is_backbone (const Lit & literal) const override virtual
Check if literal is in backbone.
Parameters
literal Literal to check
Returns
true if in backbone
Implements BackBone.
Definition at line 201 of file CheckCandidatesOneByOneWithoutAttention.cc.
References LiteralSet::get().
Referenced by CheckCandidatesOneByOneWithoutAttention::backbone_sign(), BackboneSolverAPI::Impl::compute(), BackboneSolverAPI::Impl::compute_with_assumps(), CheckCandidatesOneByOneWithoutAttention::is_backbone(), and BackboneSolverAPI::Impl::print_bb().
is_backbone() [2/2]
bool is_backbone (Var var) const override virtual
Check if variable is in backbone.
Parameters
var Variable to check
Returns
true if in backbone
Implements BackBone.
Definition at line 206 of file CheckCandidatesOneByOneWithoutAttention.cc.
References CheckCandidatesOneByOneWithoutAttention::is_backbone().
run()
void run () override virtual
Run backbone detection without activity bumping.
Implements BackBone.
Definition at line 106 of file CheckCandidatesOneByOneWithoutAttention.cc.
References LiteralSet::add(), LiteralSet::discard_from_model(), LiteralSet::remove(), and LiteralSet::size().
Referenced by BackboneSolverAPI::Impl::compute().
run_with_assumptions()
bool run_with_assumptions (const vec< Lit > & assumptions) override virtual
Run backbone detection with assumptions.
Parameters
assumptions Literals that must be satisfied
Returns
true if satisfiable under assumptions
Implements BackBone.
Definition at line 123 of file CheckCandidatesOneByOneWithoutAttention.cc.
References LiteralSet::add(), LiteralSet::clear(), LiteralSet::discard_from_model(), LiteralSet::infinite_iterator(), LiteralSet::remove(), and LiteralSet::size().
Referenced by BackboneSolverAPI::Impl::compute_with_assumps().
The documentation for this class was generated from the following files:
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/detectors/CheckCandidatesOneByOneWithoutAttention.hh
/mnt/c/strong4vm/dimacs2graphs/backbone_solver/src/detectors/CheckCandidatesOneByOneWithoutAttention.cc