Strong4VM: UVL2Dimacs Class Reference
UVL2Dimacs Class Reference
UVL to DIMACS Conversion
Main class for UVL to DIMACS conversion.
#include <UVL2Dimacs.hh>
Public Member Functions
UVL2Dimacs (bool verbose=false)
Constructor.
~UVL2Dimacs ()
Destructor.
void set_verbose (bool verbose)
Set verbose output mode.
void set_mode (ConversionMode mode)
Set conversion mode.
ConversionMode get_mode () const
Get current conversion mode.
ConversionResult convert (const std::string &input_file, const std::string &output_file)
Convert a UVL file to DIMACS format.
ConversionResult convert (const std::string &input_file, const std::string &output_file, ConversionMode mode)
Convert a UVL file to DIMACS format with specified mode.
std::string convert_to_string (const std::string &input_file, ConversionResult &result)
Convert a UVL file to DIMACS string.
std::string convert_to_string (const std::string &input_file, ConversionMode mode, ConversionResult &result)
Convert a UVL file to DIMACS string with specified mode.
Detailed Description
Main class for UVL to DIMACS conversion.
This class provides a high-level interface for converting UVL files to DIMACS CNF format. It handles all the complexity of parsing, transformation, and writing.
Example usage:
uvl2dimacs::UVL2Dimacs converter;
converter.set_verbose(true);
auto result = converter.convert("input.uvl", "output.dimacs");
if (result.success) {
    std::cout << "Converted " << result.num_features << " features to "
              << result.num_clauses << " clauses" << std::endl;
} else {
    std::cerr << "Error: " << result.error_message << std::endl;
}
Definition at line 174 of file UVL2Dimacs.hh.
Constructor & Destructor Documentation
UVL2Dimacs()
UVL2Dimacs (bool verbose = false) explicit
Constructor.
Parameters
verbose Whether to print progress messages (default: false)
~UVL2Dimacs()
~UVL2Dimacs ()
Destructor.
Member Function Documentation
convert() [1/2]
ConversionResult convert (const std::string & input_file, const std::string & output_file)
Convert a UVL file to DIMACS format.
Parameters
input_file Path to input UVL file
output_file Path to output DIMACS file
Returns
ConversionResult with success status and statistics
Referenced by Strong4VMAPI::Impl::perform_analysis().
convert() [2/2]
ConversionResult convert (const std::string & input_file, const std::string & output_file, ConversionMode mode)
Convert a UVL file to DIMACS format with specified mode.
Parameters
input_file Path to input UVL file
output_file Path to output DIMACS file
mode Conversion mode to use for this conversion
Returns
ConversionResult with success status and statistics
convert_to_string() [1/2]
std::string convert_to_string (const std::string & input_file, ConversionMode mode, ConversionResult & result)
Convert a UVL file to DIMACS string with specified mode.
Parameters
input_file Path to input UVL file
mode Conversion mode to use for this conversion
result Output parameter for conversion result
Returns
DIMACS string if successful, empty string if failed
convert_to_string() [2/2]
std::string convert_to_string (const std::string & input_file, ConversionResult & result)
Convert a UVL file to DIMACS string.
Parameters
input_file Path to input UVL file
result Output parameter for conversion result
Returns
DIMACS string if successful, empty string if failed
get_mode()
ConversionMode get_mode () const
Get current conversion mode.
Returns
The current conversion mode
set_mode()
void set_mode (ConversionMode mode)
Set conversion mode.
Parameters
mode The CNF conversion mode to use
Referenced by Strong4VMAPI::Impl::perform_analysis().
set_verbose()
void set_verbose (bool verbose)
Set verbose output mode.
Parameters
verbose If true, print progress messages during conversion
Referenced by Strong4VMAPI::Impl::perform_analysis().
The documentation for this class was generated from the following file:
/mnt/c/strong4vm/uvl2dimacs/api/include/uvl2dimacs/UVL2Dimacs.hh