Strong4VM: Parsing Utilities
Parsing Utilities
Low-level parsing functions for DIMACS format.
Classes
class StreamBuffer
Buffered character stream for reading gzipped files.
Functions
static bool isEof (StreamBuffer &in)
Check if StreamBuffer reached end of file.
static bool isEof (const char *in)
Check if C-string reached null terminator.
template<class B >
static bool isEof (B &in)
Generic EOF check for any input stream type.
template<class B >
static void skipTrueWhitespace (B &in)
Skip true whitespace (space and tab, not newline)
template<class B >
static void skipWhitespace (B &in)
Skip all whitespace including newlines.
template<class B >
static void skipLine (B &in)
Skip to end of current line.
template<class B >
static int parseInt (B &in)
Parse an integer from input stream.
template<class B >
static bool match (B &in, const char *str)
Match a string at current position (requires random access)
template<class B >
static bool eagerMatch (B &in, const char *str)
Match a string eagerly (for forward-only iterators)
Variables
static const int buffer_size = 1048576
Buffer size for StreamBuffer (1MB)
Detailed Description
Low-level parsing functions for DIMACS format.
Function Documentation
eagerMatch()
template<class B > static bool eagerMatch (B & in, const char * str) static
Match a string eagerly (for forward-only iterators)
Consumes characters from input while matching. If match fails, characters have already been consumed. Use for forward-only iterators.
Template Parameters
B Input stream type
Parameters
in Input stream to consume from
str String to match
Returns
true if string matches completely
false if match fails (partial input consumed)
Definition at line 213 of file parse_utils.hh.
isEof() [1/3]
template<class B > static bool isEof (B & in) inline static
Generic EOF check for any input stream type.
Template Parameters
B Input stream type
Parameters
in Input stream to check
Returns
true if at EOF
Definition at line 119 of file parse_utils.hh.
isEof() [2/3]
static bool isEof (const char * in) inline static
Check if C-string reached null terminator.
Parameters
in C-string pointer to check
Returns
true if at null terminator
Definition at line 110 of file parse_utils.hh.
isEof() [3/3]
static bool isEof (StreamBuffer & in) inline static
Check if StreamBuffer reached end of file.
Parameters
in Stream buffer to check
Returns
true if at EOF
Definition at line 103 of file parse_utils.hh.
Referenced by skipLine().
match()
template<class B > static bool match (B & in, const char * str) static
Match a string at current position (requires random access)
Checks if the input matches the given string without consuming characters unless there's a complete match. Requires random access iterator.
Template Parameters
B Input stream type (must support indexing)
Parameters
in Input stream to check
str String to match
Returns
true if string matches (and input is advanced)
false if no match (input unchanged)
Definition at line 189 of file parse_utils.hh.
parseInt()
template<class B > static int parseInt (B & in) static
Parse an integer from input stream.
Skips leading whitespace, handles optional sign, and parses digits. Exits with error if non-digit encountered.
Template Parameters
B Input stream type
Parameters
in Input stream to parse from
Returns
Parsed integer value
Definition at line 164 of file parse_utils.hh.
References skipWhitespace().
skipLine()
template<class B > static void skipLine (B & in) static
Skip to end of current line.
Template Parameters
B Input stream type
Parameters
in Input stream to advance
Definition at line 147 of file parse_utils.hh.
References isEof().
Referenced by DIMACSReader::read().
skipTrueWhitespace()
template<class B > static void skipTrueWhitespace (B & in) static
Skip true whitespace (space and tab, not newline)
Template Parameters
B Input stream type
Parameters
in Input stream to advance
Definition at line 127 of file parse_utils.hh.
skipWhitespace()
template<class B > static void skipWhitespace (B & in) static
Skip all whitespace including newlines.
Template Parameters
B Input stream type
Parameters
in Input stream to advance
Definition at line 137 of file parse_utils.hh.
Referenced by parseInt().
Variable Documentation
buffer_size
const int buffer_size = 1048576 static
Buffer size for StreamBuffer (1MB)
Definition at line 46 of file parse_utils.hh.